### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by leijdekkers** [mkhoiron/Actionsheet-android#1]
Great library! Would it be possible to add the feature to set the fontsize of the title, cancelTitle and data items? So something like this:

ActionSheet(this, data)
                .setTitle("Title here")
                .setFontTitle(12sp)
                .setFontCancelTitle(10sp)
                .setFontData(12sp)
                 .....
                .create(this)

**Comment by mkhoiron** [comment]
Of course. I will add it this week

**Comment by khoyron** [comment]
Of course. I will add it this week

**Comment by khoyron** [comment]
i have already added this feature
https://github.com/mkhoiron/Actionsheet-android#update-fitur

implementation 'com.github.mkhoiron:Actionsheet-android:3'
