### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by cristibaluta** [mkhoiron/Actionsheet-android#2]
I don't know why, i'm a beginner, but i can't install it:
ERROR: Failed to resolve: com.github.mkhoiron:Actionsheet-android:0.1

**Comment by khoyron** [comment]
I didn't find any problems :  implementation 'com.github.mkhoiron: Actionsheet-android: 0.1'

**Comment by cristibaluta** [comment]
There was something extra i needed to do, i don't recall what but i got suspicious when none of the libs i wanted to install work.
